server:
  port: 3330
spring:
  application:
    name: turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true
turbine:
  app-config: dashboard
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
