server:
  port: 3333
spring:
  application:
    name: euraka-feign
  zipkin:
    base-url: http://localhost:4440
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
management:
  security:
    enabled: false
