management:
  security:
    enabled: false
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
spring:
  application:
    name: trace-two
  zipkin:
    base-url: http://localhost:9411
#    enabled: true
  sleuth:
    sampler:
      percentage: 1.0